[phases.install]
cmds = ['npm ci && npm install --save-dev vite laravel-vite-plugin && npm install --save-dev @vitejs/plugin-vue']

[build]
builder = "NIXPACKS"

[deploy]
runtime = "PODMAN"
numReplicas = 1
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10