[build]
builder = "NIXPACKS"

[build.nixpacksPlan.phases.install]
cmds = ['mkdir -p /var/log/nginx && mkdir -p /var/cache/nginx && composer install --ignore-platform-reqs && composer require laravel/breeze --dev && php artisan breeze:install vue && npm ci && npm install --save-dev vite laravel-vite-plugin && npm install --save-dev @vitejs/plugin-vue']

[deploy]
runtime = "PODMAN"
numReplicas = 1
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10